///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TCOS_POC_DEMOAPP
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Fill_In_Form_And_Click_Add_Entry recording.
    /// </summary>
    [TestModule("94ef9041-3ac8-49cf-81f8-af08f5ac75a6", ModuleType.Recording, 1)]
    public partial class Fill_In_Form_And_Click_Add_Entry : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TCOS_POC_DEMOAPPRepository repository.
        /// </summary>
        public static TCOS_POC_DEMOAPPRepository repo = TCOS_POC_DEMOAPPRepository.Instance;

        static Fill_In_Form_And_Click_Add_Entry instance = new Fill_In_Form_And_Click_Add_Entry();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Fill_In_Form_And_Click_Add_Entry()
        {
            Firstname = "quest";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Fill_In_Form_And_Click_Add_Entry Instance
        {
            get { return instance; }
        }

#region Variables

        string _Firstname;

        /// <summary>
        /// Gets or sets the value of variable Firstname.
        /// </summary>
        [TestVariable("5d8cb0ac-697a-4d16-9a01-209e8b93d384")]
        public string Firstname
        {
            get { return _Firstname; }
            set { _Firstname = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.UIElementTestArea' at 62;17.", repo.RxMainFrame.UIElementTestAreaInfo, new RecordItemIndex(0));
            repo.RxMainFrame.UIElementTestArea.Click("62;17");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabUIElements.RdbGreenLight' at 10;9.", repo.RxMainFrame.RxTabUIElements.RdbGreenLightInfo, new RecordItemIndex(1));
            repo.RxMainFrame.RxTabUIElements.RdbGreenLight.Click("10;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'RxMainFrame.RxTabUIElements.PnlColourPanel'.", repo.RxMainFrame.RxTabUIElements.PnlColourPanelInfo, new RecordItemIndex(2));
            Validate.Exists(repo.RxMainFrame.RxTabUIElements.PnlColourPanelInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabUIElements.RdbRedLight' at 6;12.", repo.RxMainFrame.RxTabUIElements.RdbRedLightInfo, new RecordItemIndex(3));
            repo.RxMainFrame.RxTabUIElements.RdbRedLight.Click("6;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'RxMainFrame.RxTabUIElements.PnlColourPanel'.", repo.RxMainFrame.RxTabUIElements.PnlColourPanelInfo, new RecordItemIndex(4));
            Validate.Exists(repo.RxMainFrame.RxTabUIElements.PnlColourPanelInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabUIElements.BtnButton1' at 44;9.", repo.RxMainFrame.RxTabUIElements.BtnButton1Info, new RecordItemIndex(5));
            repo.RxMainFrame.RxTabUIElements.BtnButton1.Click("44;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabUIElements.Down' at 7;9.", repo.RxMainFrame.RxTabUIElements.DownInfo, new RecordItemIndex(6));
            repo.RxMainFrame.RxTabUIElements.Down.Click("7;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabUIElements.Down' at 7;9.", repo.RxMainFrame.RxTabUIElements.DownInfo, new RecordItemIndex(7));
            repo.RxMainFrame.RxTabUIElements.Down.Click("7;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabUIElements.Down' at 7;9.", repo.RxMainFrame.RxTabUIElements.DownInfo, new RecordItemIndex(8));
            repo.RxMainFrame.RxTabUIElements.Down.Click("7;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabUIElements.Down' at 11;14.", repo.RxMainFrame.RxTabUIElements.DownInfo, new RecordItemIndex(9));
            repo.RxMainFrame.RxTabUIElements.Down.Click("11;14");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'RxMainFrame.RxTabUIElements.Down' at 11;14.", repo.RxMainFrame.RxTabUIElements.DownInfo, new RecordItemIndex(10));
            repo.RxMainFrame.RxTabUIElements.Down.DoubleClick("11;14");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabUIElements.TreeView' at 14;10.", repo.RxMainFrame.RxTabUIElements.TreeViewInfo, new RecordItemIndex(11));
            repo.RxMainFrame.RxTabUIElements.TreeView.Click("14;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Down}{Down}{Down}{Down}{Down}{Down}{Down}{Down}' with focus on 'RxMainFrame.RxTabUIElements.TreeView'.", repo.RxMainFrame.RxTabUIElements.TreeViewInfo, new RecordItemIndex(12));
            repo.RxMainFrame.RxTabUIElements.TreeView.PressKeys("{Down}{Down}{Down}{Down}{Down}{Down}{Down}{Down}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabUIElements.TreeView' at 11;11.", repo.RxMainFrame.RxTabUIElements.TreeViewInfo, new RecordItemIndex(13));
            repo.RxMainFrame.RxTabUIElements.TreeView.Click("11;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabUIElements.TreeView' at 9;23.", repo.RxMainFrame.RxTabUIElements.TreeViewInfo, new RecordItemIndex(14));
            repo.RxMainFrame.RxTabUIElements.TreeView.Click("9;23");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Down}{Down}{Down}{Down}{Down}{Down}{Down}{Down}{Down}{Down}' with focus on 'RxMainFrame.RxTabUIElements.TreeView'.", repo.RxMainFrame.RxTabUIElements.TreeViewInfo, new RecordItemIndex(15));
            repo.RxMainFrame.RxTabUIElements.TreeView.PressKeys("{Down}{Down}{Down}{Down}{Down}{Down}{Down}{Down}{Down}{Down}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Up}{Up}{Up}{Up 2}{Up}{Up}{Up}{Up}{Up}' with focus on 'RxMainFrame.RxTabUIElements.TreeView'.", repo.RxMainFrame.RxTabUIElements.TreeViewInfo, new RecordItemIndex(16));
            repo.RxMainFrame.RxTabUIElements.TreeView.PressKeys("{Up}{Up}{Up}{Up 2}{Up}{Up}{Up}{Up}{Up}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabUIElements.TreeView' at 14;25.", repo.RxMainFrame.RxTabUIElements.TreeViewInfo, new RecordItemIndex(17));
            repo.RxMainFrame.RxTabUIElements.TreeView.Click("14;25");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabUIElements.TreeView' at 14;48.", repo.RxMainFrame.RxTabUIElements.TreeViewInfo, new RecordItemIndex(18));
            repo.RxMainFrame.RxTabUIElements.TreeView.Click("14;48");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Down}{Down}{Down}{Down}{Down}{Down}{Down}' with focus on 'RxMainFrame.RxTabUIElements.TreeView'.", repo.RxMainFrame.RxTabUIElements.TreeViewInfo, new RecordItemIndex(19));
            repo.RxMainFrame.RxTabUIElements.TreeView.PressKeys("{Down}{Down}{Down}{Down}{Down}{Down}{Down}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabUIElements.TreeView' at 12;45.", repo.RxMainFrame.RxTabUIElements.TreeViewInfo, new RecordItemIndex(20));
            repo.RxMainFrame.RxTabUIElements.TreeView.Click("12;45");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabUIElements.TreeView' at 12;66.", repo.RxMainFrame.RxTabUIElements.TreeViewInfo, new RecordItemIndex(21));
            repo.RxMainFrame.RxTabUIElements.TreeView.Click("12;66");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabUIElements.WebTesting' at 23;4.", repo.RxMainFrame.RxTabUIElements.WebTestingInfo, new RecordItemIndex(22));
            repo.RxMainFrame.RxTabUIElements.WebTesting.Click("23;4");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Down}{Down}' with focus on 'RxMainFrame.RxTabUIElements.WebTesting'.", repo.RxMainFrame.RxTabUIElements.WebTestingInfo, new RecordItemIndex(23));
            repo.RxMainFrame.RxTabUIElements.WebTesting.PressKeys("{Down}{Down}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabUIElements.TreeView' at 9;66.", repo.RxMainFrame.RxTabUIElements.TreeViewInfo, new RecordItemIndex(24));
            repo.RxMainFrame.RxTabUIElements.TreeView.Click("9;66");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabUIElements.TreeView' at 14;86.", repo.RxMainFrame.RxTabUIElements.TreeViewInfo, new RecordItemIndex(25));
            repo.RxMainFrame.RxTabUIElements.TreeView.Click("14;86");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Down}{Down 7}{Down 2}{Down}{Down}{Down}{Down}' with focus on 'RxMainFrame.RxTabUIElements.TreeView'.", repo.RxMainFrame.RxTabUIElements.TreeViewInfo, new RecordItemIndex(26));
            repo.RxMainFrame.RxTabUIElements.TreeView.PressKeys("{Down}{Down 7}{Down 2}{Down}{Down}{Down}{Down}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Up 16}' with focus on 'RxMainFrame.RxTabUIElements.TreeView'.", repo.RxMainFrame.RxTabUIElements.TreeViewInfo, new RecordItemIndex(27));
            repo.RxMainFrame.RxTabUIElements.TreeView.PressKeys("{Up 16}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabUIElements.TreeView' at 11;63.", repo.RxMainFrame.RxTabUIElements.TreeViewInfo, new RecordItemIndex(28));
            repo.RxMainFrame.RxTabUIElements.TreeView.Click("11;63");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabUIElements.TreeView' at 13;99.", repo.RxMainFrame.RxTabUIElements.TreeViewInfo, new RecordItemIndex(29));
            repo.RxMainFrame.RxTabUIElements.TreeView.Click("13;99");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Down}{Down 13}' with focus on 'RxMainFrame.RxTabUIElements.TreeView'.", repo.RxMainFrame.RxTabUIElements.TreeViewInfo, new RecordItemIndex(30));
            repo.RxMainFrame.RxTabUIElements.TreeView.PressKeys("{Down}{Down 13}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabUIElements.TreeView' at 14;46.", repo.RxMainFrame.RxTabUIElements.TreeViewInfo, new RecordItemIndex(31));
            repo.RxMainFrame.RxTabUIElements.TreeView.Click("14;46");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabUIElements.TreeView' at 10;118.", repo.RxMainFrame.RxTabUIElements.TreeViewInfo, new RecordItemIndex(32));
            repo.RxMainFrame.RxTabUIElements.TreeView.Click("10;118");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Down}{Down}{Down}{Down}{Down}' with focus on 'RxMainFrame.RxTabUIElements.TreeView'.", repo.RxMainFrame.RxTabUIElements.TreeViewInfo, new RecordItemIndex(33));
            repo.RxMainFrame.RxTabUIElements.TreeView.PressKeys("{Down}{Down}{Down}{Down}{Down}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabUIElements.TreeView' at 13;78.", repo.RxMainFrame.RxTabUIElements.TreeViewInfo, new RecordItemIndex(34));
            repo.RxMainFrame.RxTabUIElements.TreeView.Click("13;78");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.DataGridView1.FirstNameRow0' at 32;10.", repo.RxMainFrame.DataGridView1.FirstNameRow0Info, new RecordItemIndex(35));
            repo.RxMainFrame.DataGridView1.FirstNameRow0.Click("32;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Down}{Down}{Down}{Down}{Down}{Down}{Down}{Down}{Down}' with focus on 'RxMainFrame.DataGridView1.FirstNameRow0'.", repo.RxMainFrame.DataGridView1.FirstNameRow0Info, new RecordItemIndex(36));
            repo.RxMainFrame.DataGridView1.FirstNameRow0.PressKeys("{Down}{Down}{Down}{Down}{Down}{Down}{Down}{Down}{Down}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.DataGridView1.IORow7' at 11;5.", repo.RxMainFrame.DataGridView1.IORow7Info, new RecordItemIndex(37));
            repo.RxMainFrame.DataGridView1.IORow7.Click("11;5");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.DataGridView1.Row7' at 18;8.", repo.RxMainFrame.DataGridView1.Row7Info, new RecordItemIndex(38));
            repo.RxMainFrame.DataGridView1.Row7.Click("18;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.DataGridView1.FirstNameRow7' at 47;1.", repo.RxMainFrame.DataGridView1.FirstNameRow7Info, new RecordItemIndex(39));
            repo.RxMainFrame.DataGridView1.FirstNameRow7.Click("47;1");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.DataGridView1.FirstNameRow7' at 49;2.", repo.RxMainFrame.DataGridView1.FirstNameRow7Info, new RecordItemIndex(40));
            repo.RxMainFrame.DataGridView1.FirstNameRow7.Click("49;2");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.DataGridView1.FirstNameRow7' at 49;2.", repo.RxMainFrame.DataGridView1.FirstNameRow7Info, new RecordItemIndex(41));
            repo.RxMainFrame.DataGridView1.FirstNameRow7.Click("49;2");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Back}{Back}{Back}{Back}{Back}{Back}Nicole' with focus on 'RxMainFrame.DataGridView1.FirstNameRow7'.", repo.RxMainFrame.DataGridView1.FirstNameRow7Info, new RecordItemIndex(42));
            repo.RxMainFrame.DataGridView1.FirstNameRow7.PressKeys("{Back}{Back}{Back}{Back}{Back}{Back}Nicole");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}' with focus on 'RxMainFrame.DataGridView1.FirstNameRow7'.", repo.RxMainFrame.DataGridView1.FirstNameRow7Info, new RecordItemIndex(43));
            repo.RxMainFrame.DataGridView1.FirstNameRow7.PressKeys("{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'RxMainFrame.RxTabUIElements.Position' at 218;11.", repo.RxMainFrame.RxTabUIElements.PositionInfo, new RecordItemIndex(44));
            repo.RxMainFrame.RxTabUIElements.Position.MoveTo("218;11");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'RxMainFrame.RxTabUIElements.Position' at 236;11.", repo.RxMainFrame.RxTabUIElements.PositionInfo, new RecordItemIndex(45));
            repo.RxMainFrame.RxTabUIElements.Position.MoveTo("236;11");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
