///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TCOS_POC_DEMOAPP
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Navigate_to_Image_based_automation_tab recording.
    /// </summary>
    [TestModule("0c9a99b6-38af-4744-969e-856e62566638", ModuleType.Recording, 1)]
    public partial class Navigate_to_Image_based_automation_tab : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TCOS_POC_DEMOAPPRepository repository.
        /// </summary>
        public static TCOS_POC_DEMOAPPRepository repo = TCOS_POC_DEMOAPPRepository.Instance;

        static Navigate_to_Image_based_automation_tab instance = new Navigate_to_Image_based_automation_tab();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Navigate_to_Image_based_automation_tab()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Navigate_to_Image_based_automation_tab Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.PageTabList' at 17;10.", repo.RxMainFrame.PageTabListInfo, new RecordItemIndex(0));
            repo.RxMainFrame.PageTabList.Click(new Location(PageTabList_Screenshot2, "17;10", PageTabList_Screenshot2_Options));
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'soma' with focus on 'RxMainFrame.RxTabStandard.TxtFirstName'.", repo.RxMainFrame.RxTabStandard.TxtFirstNameInfo, new RecordItemIndex(1));
            repo.RxMainFrame.RxTabStandard.TxtFirstName.EnsureVisible();
            Keyboard.Press("soma");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'g' with focus on 'RxMainFrame.RxTabStandard.TxtLastName'.", repo.RxMainFrame.RxTabStandard.TxtLastNameInfo, new RecordItemIndex(2));
            repo.RxMainFrame.RxTabStandard.TxtLastName.PressKeys("g");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabStandard.CmbDepartment' at 435;12.", repo.RxMainFrame.RxTabStandard.CmbDepartmentInfo, new RecordItemIndex(3));
            repo.RxMainFrame.RxTabStandard.CmbDepartment.Click("435;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '39' with focus on 'RxMainFrame'.", repo.RxMainFrame.SelfInfo, new RecordItemIndex(4));
            repo.RxMainFrame.Self.EnsureVisible();
            Keyboard.Press("39");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabStandard.UpDownEdit' at 392;16.", repo.RxMainFrame.RxTabStandard.UpDownEditInfo, new RecordItemIndex(5));
            repo.RxMainFrame.RxTabStandard.UpDownEdit.Click("392;16");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabStandard.BtnAddPerson' at 24;9.", repo.RxMainFrame.RxTabStandard.BtnAddPersonInfo, new RecordItemIndex(6));
            repo.RxMainFrame.RxTabStandard.BtnAddPerson.Click("24;9");
            Delay.Milliseconds(18930);
            
        }

#region Image Feature Data
        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        CompressedImage PageTabList_Screenshot2
        { get { return repo.RxMainFrame.PageTabListInfo.GetScreenshot2(new Rectangle(232, 76, 23, 14)); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        Imaging.FindOptions PageTabList_Screenshot2_Options
        { get { return Imaging.FindOptions.Default; } }

#endregion
    }
#pragma warning restore 0436
}
