///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace TCOS_POC_DEMOAPP
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the TCOS_POC_DEMOAPPRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("95af092a-f552-4cd1-bced-e40668d18b4e")]
    public partial class TCOS_POC_DEMOAPPRepository : RepoGenBaseFolder
    {
        static TCOS_POC_DEMOAPPRepository instance = new TCOS_POC_DEMOAPPRepository();
        TCOS_POC_DEMOAPPRepositoryFolders.RxMainFrameAppFolder _rxmainframe;

        /// <summary>
        /// Gets the singleton class instance representing the TCOS_POC_DEMOAPPRepository element repository.
        /// </summary>
        [RepositoryFolder("95af092a-f552-4cd1-bced-e40668d18b4e")]
        public static TCOS_POC_DEMOAPPRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public TCOS_POC_DEMOAPPRepository() 
            : base("TCOS_POC_DEMOAPPRepository", "/", null, 0, false, "95af092a-f552-4cd1-bced-e40668d18b4e", ".\\RepositoryImages\\TCOS_POC_DEMOAPPRepository95af092a.rximgres")
        {
            _rxmainframe = new TCOS_POC_DEMOAPPRepositoryFolders.RxMainFrameAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("95af092a-f552-4cd1-bced-e40668d18b4e")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The RxMainFrame folder.
        /// </summary>
        [RepositoryFolder("a73f68ae-7fc1-4054-ac4f-8400d31286c7")]
        public virtual TCOS_POC_DEMOAPPRepositoryFolders.RxMainFrameAppFolder RxMainFrame
        {
            get { return _rxmainframe; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class TCOS_POC_DEMOAPPRepositoryFolders
    {
        /// <summary>
        /// The RxMainFrameAppFolder folder.
        /// </summary>
        [RepositoryFolder("a73f68ae-7fc1-4054-ac4f-8400d31286c7")]
        public partial class RxMainFrameAppFolder : RepoGenBaseFolder
        {
            TCOS_POC_DEMOAPPRepositoryFolders.RxTabIntroductionFolder _rxtabintroduction;
            TCOS_POC_DEMOAPPRepositoryFolders.RxTabUploadFolder _rxtabupload;
            TCOS_POC_DEMOAPPRepositoryFolders.RxTabUIElementsFolder _rxtabuielements;
            TCOS_POC_DEMOAPPRepositoryFolders.DataGridView1Folder _datagridview1;
            RepoItemInfo _testdatabaseInfo;
            RepoItemInfo _imagebasedautomationInfo;
            RepoItemInfo _uielementtestareaInfo;
            RepoItemInfo _uploadtestingInfo;
            RepoItemInfo _dynamicidsInfo;
            RepoItemInfo _objectidentificationInfo;
            RepoItemInfo _rdbgreenlightInfo;
            RepoItemInfo _rdbredlightInfo;
            RepoItemInfo _pnlcolourpanelInfo;
            RepoItemInfo _btnbutton1Info;
            RepoItemInfo _downInfo;
            RepoItemInfo _webtestingInfo;
            RepoItemInfo _ranorexstudiodemoapplicationInfo;

            /// <summary>
            /// Creates a new RxMainFrame  folder.
            /// </summary>
            public RxMainFrameAppFolder(RepoGenBaseFolder parentFolder) :
                    base("RxMainFrame", "/form[@controlname='RxMainFrame']", parentFolder, 30000, null, true, "a73f68ae-7fc1-4054-ac4f-8400d31286c7", "")
            {
                _rxtabintroduction = new TCOS_POC_DEMOAPPRepositoryFolders.RxTabIntroductionFolder(this);
                _rxtabupload = new TCOS_POC_DEMOAPPRepositoryFolders.RxTabUploadFolder(this);
                _rxtabuielements = new TCOS_POC_DEMOAPPRepositoryFolders.RxTabUIElementsFolder(this);
                _datagridview1 = new TCOS_POC_DEMOAPPRepositoryFolders.DataGridView1Folder(this);
                _testdatabaseInfo = new RepoItemInfo(this, "TestDatabase", "?/?/tabpage[@accessiblename='Test database']", 30000, null, "c31ea0f4-0807-4bae-a500-7eef55866515");
                _imagebasedautomationInfo = new RepoItemInfo(this, "ImageBasedAutomation", "?/?/tabpage[@accessiblename='Image-based automation']", 30000, null, "8aea560f-649f-4aca-9a18-b13ab214214c");
                _uielementtestareaInfo = new RepoItemInfo(this, "UIElementTestArea", "?/?/tabpage[@accessiblename='UI-element test area']", 30000, null, "dae9d3e3-fdeb-44c7-919c-6f9b3ea90897");
                _uploadtestingInfo = new RepoItemInfo(this, "UploadTesting", "?/?/tabpage[@accessiblename='Upload testing']", 30000, null, "ab27b977-d00e-4f92-8332-c841f3e8d06b");
                _dynamicidsInfo = new RepoItemInfo(this, "DynamicIDs", "?/?/tabpage[@accessiblename='Dynamic IDs']", 30000, null, "5eda5d09-995a-41cb-b86f-10e9921cc3cb");
                _objectidentificationInfo = new RepoItemInfo(this, "ObjectIdentification", "?/?/tabpage[@accessiblename='Object identification']", 30000, null, "3bde9fb0-d961-4149-9283-e800339dee73");
                _rdbgreenlightInfo = new RepoItemInfo(this, "RdbGreenLight", "?/?/tabpage[@controlname='RxTabUIElements']/container[@controlname='grpBox']/?/?/radiobutton[@controlname='rdbGreenLight']", 30000, null, "f5563d1f-b299-4d6d-b34a-d15626a56062");
                _rdbredlightInfo = new RepoItemInfo(this, "RdbRedLight", "?/?/tabpage[@controlname='RxTabUIElements']/container[@controlname='grpBox']/?/?/radiobutton[@controlname='rdbRedLight']", 30000, null, "651900b9-2bf1-4aec-b14a-c6ca86b27ef4");
                _pnlcolourpanelInfo = new RepoItemInfo(this, "PnlColourPanel", "?/?/tabpage[@controlname='RxTabUIElements']/container[@controlname='grpBox']/?/?/container[@controlname='pnlColourPanel']", 30000, null, "8f1af682-269e-493b-adca-09bfec77f0fc");
                _btnbutton1Info = new RepoItemInfo(this, "BtnButton1", "?/?/tabpage[@controlname='RxTabUIElements']/?/?/button[@controlname='btnButton1']", 30000, null, "4988a103-f697-47db-a03f-876d7fae7c6b");
                _downInfo = new RepoItemInfo(this, "Down", "?/?/tabpage[@controlname='RxTabUIElements']/container[@controlname='grpBox']/?/?/list[@controlname='lstTestBox']/?/?/button[@text='Down']", 30000, null, "297c4049-252c-491a-a43b-56bffa7181e8");
                _webtestingInfo = new RepoItemInfo(this, "WebTesting", "?/?/tabpage[@controlname='RxTabUIElements']/tree[@controlname='treTestTreeView']//treeitem[@accessiblename='Web testing']", 30000, null, "ac42582a-64c1-4a47-87a7-1b75a7e70b35");
                _ranorexstudiodemoapplicationInfo = new RepoItemInfo(this, "RanorexStudioDemoApplication", "titlebar[@accessiblerole='TitleBar']", 30000, null, "bd962fb3-3ab7-4c46-8ebd-7c6bf2df003b");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("a73f68ae-7fc1-4054-ac4f-8400d31286c7")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a73f68ae-7fc1-4054-ac4f-8400d31286c7")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The TestDatabase item.
            /// </summary>
            [RepositoryItem("c31ea0f4-0807-4bae-a500-7eef55866515")]
            public virtual Ranorex.TabPage TestDatabase
            {
                get
                {
                    return _testdatabaseInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The TestDatabase item info.
            /// </summary>
            [RepositoryItemInfo("c31ea0f4-0807-4bae-a500-7eef55866515")]
            public virtual RepoItemInfo TestDatabaseInfo
            {
                get
                {
                    return _testdatabaseInfo;
                }
            }

            /// <summary>
            /// The ImageBasedAutomation item.
            /// </summary>
            [RepositoryItem("8aea560f-649f-4aca-9a18-b13ab214214c")]
            public virtual Ranorex.TabPage ImageBasedAutomation
            {
                get
                {
                    return _imagebasedautomationInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The ImageBasedAutomation item info.
            /// </summary>
            [RepositoryItemInfo("8aea560f-649f-4aca-9a18-b13ab214214c")]
            public virtual RepoItemInfo ImageBasedAutomationInfo
            {
                get
                {
                    return _imagebasedautomationInfo;
                }
            }

            /// <summary>
            /// The UIElementTestArea item.
            /// </summary>
            [RepositoryItem("dae9d3e3-fdeb-44c7-919c-6f9b3ea90897")]
            public virtual Ranorex.TabPage UIElementTestArea
            {
                get
                {
                    return _uielementtestareaInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The UIElementTestArea item info.
            /// </summary>
            [RepositoryItemInfo("dae9d3e3-fdeb-44c7-919c-6f9b3ea90897")]
            public virtual RepoItemInfo UIElementTestAreaInfo
            {
                get
                {
                    return _uielementtestareaInfo;
                }
            }

            /// <summary>
            /// The UploadTesting item.
            /// </summary>
            [RepositoryItem("ab27b977-d00e-4f92-8332-c841f3e8d06b")]
            public virtual Ranorex.TabPage UploadTesting
            {
                get
                {
                    return _uploadtestingInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The UploadTesting item info.
            /// </summary>
            [RepositoryItemInfo("ab27b977-d00e-4f92-8332-c841f3e8d06b")]
            public virtual RepoItemInfo UploadTestingInfo
            {
                get
                {
                    return _uploadtestingInfo;
                }
            }

            /// <summary>
            /// The DynamicIDs item.
            /// </summary>
            [RepositoryItem("5eda5d09-995a-41cb-b86f-10e9921cc3cb")]
            public virtual Ranorex.TabPage DynamicIDs
            {
                get
                {
                    return _dynamicidsInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The DynamicIDs item info.
            /// </summary>
            [RepositoryItemInfo("5eda5d09-995a-41cb-b86f-10e9921cc3cb")]
            public virtual RepoItemInfo DynamicIDsInfo
            {
                get
                {
                    return _dynamicidsInfo;
                }
            }

            /// <summary>
            /// The ObjectIdentification item.
            /// </summary>
            [RepositoryItem("3bde9fb0-d961-4149-9283-e800339dee73")]
            public virtual Ranorex.TabPage ObjectIdentification
            {
                get
                {
                    return _objectidentificationInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The ObjectIdentification item info.
            /// </summary>
            [RepositoryItemInfo("3bde9fb0-d961-4149-9283-e800339dee73")]
            public virtual RepoItemInfo ObjectIdentificationInfo
            {
                get
                {
                    return _objectidentificationInfo;
                }
            }

            /// <summary>
            /// The RdbGreenLight item.
            /// </summary>
            [RepositoryItem("f5563d1f-b299-4d6d-b34a-d15626a56062")]
            public virtual Ranorex.RadioButton RdbGreenLight
            {
                get
                {
                    return _rdbgreenlightInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The RdbGreenLight item info.
            /// </summary>
            [RepositoryItemInfo("f5563d1f-b299-4d6d-b34a-d15626a56062")]
            public virtual RepoItemInfo RdbGreenLightInfo
            {
                get
                {
                    return _rdbgreenlightInfo;
                }
            }

            /// <summary>
            /// The RdbRedLight item.
            /// </summary>
            [RepositoryItem("651900b9-2bf1-4aec-b14a-c6ca86b27ef4")]
            public virtual Ranorex.RadioButton RdbRedLight
            {
                get
                {
                    return _rdbredlightInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The RdbRedLight item info.
            /// </summary>
            [RepositoryItemInfo("651900b9-2bf1-4aec-b14a-c6ca86b27ef4")]
            public virtual RepoItemInfo RdbRedLightInfo
            {
                get
                {
                    return _rdbredlightInfo;
                }
            }

            /// <summary>
            /// The PnlColourPanel item.
            /// </summary>
            [RepositoryItem("8f1af682-269e-493b-adca-09bfec77f0fc")]
            public virtual Ranorex.Container PnlColourPanel
            {
                get
                {
                    return _pnlcolourpanelInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The PnlColourPanel item info.
            /// </summary>
            [RepositoryItemInfo("8f1af682-269e-493b-adca-09bfec77f0fc")]
            public virtual RepoItemInfo PnlColourPanelInfo
            {
                get
                {
                    return _pnlcolourpanelInfo;
                }
            }

            /// <summary>
            /// The BtnButton1 item.
            /// </summary>
            [RepositoryItem("4988a103-f697-47db-a03f-876d7fae7c6b")]
            public virtual Ranorex.Button BtnButton1
            {
                get
                {
                    return _btnbutton1Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtnButton1 item info.
            /// </summary>
            [RepositoryItemInfo("4988a103-f697-47db-a03f-876d7fae7c6b")]
            public virtual RepoItemInfo BtnButton1Info
            {
                get
                {
                    return _btnbutton1Info;
                }
            }

            /// <summary>
            /// The Down item.
            /// </summary>
            [RepositoryItem("297c4049-252c-491a-a43b-56bffa7181e8")]
            public virtual Ranorex.Button Down
            {
                get
                {
                    return _downInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Down item info.
            /// </summary>
            [RepositoryItemInfo("297c4049-252c-491a-a43b-56bffa7181e8")]
            public virtual RepoItemInfo DownInfo
            {
                get
                {
                    return _downInfo;
                }
            }

            /// <summary>
            /// The WebTesting item.
            /// </summary>
            [RepositoryItem("ac42582a-64c1-4a47-87a7-1b75a7e70b35")]
            public virtual Ranorex.TreeItem WebTesting
            {
                get
                {
                    return _webtestingInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The WebTesting item info.
            /// </summary>
            [RepositoryItemInfo("ac42582a-64c1-4a47-87a7-1b75a7e70b35")]
            public virtual RepoItemInfo WebTestingInfo
            {
                get
                {
                    return _webtestingInfo;
                }
            }

            /// <summary>
            /// The RanorexStudioDemoApplication item.
            /// </summary>
            [RepositoryItem("bd962fb3-3ab7-4c46-8ebd-7c6bf2df003b")]
            public virtual Ranorex.TitleBar RanorexStudioDemoApplication
            {
                get
                {
                    return _ranorexstudiodemoapplicationInfo.CreateAdapter<Ranorex.TitleBar>(true);
                }
            }

            /// <summary>
            /// The RanorexStudioDemoApplication item info.
            /// </summary>
            [RepositoryItemInfo("bd962fb3-3ab7-4c46-8ebd-7c6bf2df003b")]
            public virtual RepoItemInfo RanorexStudioDemoApplicationInfo
            {
                get
                {
                    return _ranorexstudiodemoapplicationInfo;
                }
            }

            /// <summary>
            /// The RxTabIntroduction folder.
            /// </summary>
            [RepositoryFolder("76cf1697-2d1a-4453-bbc6-a8334c0668b6")]
            public virtual TCOS_POC_DEMOAPPRepositoryFolders.RxTabIntroductionFolder RxTabIntroduction
            {
                get { return _rxtabintroduction; }
            }

            /// <summary>
            /// The RxTabUpload folder.
            /// </summary>
            [RepositoryFolder("bb3fa0c3-0933-476b-9e04-c47fd826449c")]
            public virtual TCOS_POC_DEMOAPPRepositoryFolders.RxTabUploadFolder RxTabUpload
            {
                get { return _rxtabupload; }
            }

            /// <summary>
            /// The RxTabUIElements folder.
            /// </summary>
            [RepositoryFolder("fdebd0ee-f338-4434-a04f-843fa5704081")]
            public virtual TCOS_POC_DEMOAPPRepositoryFolders.RxTabUIElementsFolder RxTabUIElements
            {
                get { return _rxtabuielements; }
            }

            /// <summary>
            /// The DataGridView1 folder.
            /// </summary>
            [RepositoryFolder("72cf1af4-47cb-4905-8594-83c2002d30d5")]
            public virtual TCOS_POC_DEMOAPPRepositoryFolders.DataGridView1Folder DataGridView1
            {
                get { return _datagridview1; }
            }
        }

        /// <summary>
        /// The RxTabIntroductionFolder folder.
        /// </summary>
        [RepositoryFolder("76cf1697-2d1a-4453-bbc6-a8334c0668b6")]
        public partial class RxTabIntroductionFolder : RepoGenBaseFolder
        {
            RepoItemInfo _enteryournameInfo;
            RepoItemInfo _btnsubmitusernameInfo;
            RepoItemInfo _resetInfo;
            RepoItemInfo _lblwelcomemessageInfo;

            /// <summary>
            /// Creates a new RxTabIntroduction  folder.
            /// </summary>
            public RxTabIntroductionFolder(RepoGenBaseFolder parentFolder) :
                    base("RxTabIntroduction", "?/?/tabpage[@controlname='RxTabIntroduction']", parentFolder, 30000, null, false, "76cf1697-2d1a-4453-bbc6-a8334c0668b6", "")
            {
                _enteryournameInfo = new RepoItemInfo(this, "EnterYourName", "?/?/text[@accessiblename='Enter your name']", 30000, null, "0e7b0e85-908d-4666-a04e-36f3f4b46b50");
                _btnsubmitusernameInfo = new RepoItemInfo(this, "BtnSubmitUserName", "button[@controlname='btnSubmitUserName']", 30000, null, "ce836688-52c1-4bf4-9170-91811c99d76d");
                _resetInfo = new RepoItemInfo(this, "Reset", "link[@controlname='RxLinkBtnReset']/?/?/link[@accessiblename='Reset']", 30000, null, "abc85cba-b18c-43d6-a0d8-3ae2585e0d66");
                _lblwelcomemessageInfo = new RepoItemInfo(this, "LblWelcomeMessage", "text[@controlname='lblWelcomeMessage']", 30000, null, "18a4556e-864a-4ab9-ab77-e5a7383da0b6");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("76cf1697-2d1a-4453-bbc6-a8334c0668b6")]
            public virtual Ranorex.TabPage Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("76cf1697-2d1a-4453-bbc6-a8334c0668b6")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The EnterYourName item.
            /// </summary>
            [RepositoryItem("0e7b0e85-908d-4666-a04e-36f3f4b46b50")]
            public virtual Ranorex.Text EnterYourName
            {
                get
                {
                    return _enteryournameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The EnterYourName item info.
            /// </summary>
            [RepositoryItemInfo("0e7b0e85-908d-4666-a04e-36f3f4b46b50")]
            public virtual RepoItemInfo EnterYourNameInfo
            {
                get
                {
                    return _enteryournameInfo;
                }
            }

            /// <summary>
            /// The BtnSubmitUserName item.
            /// </summary>
            [RepositoryItem("ce836688-52c1-4bf4-9170-91811c99d76d")]
            public virtual Ranorex.Button BtnSubmitUserName
            {
                get
                {
                    return _btnsubmitusernameInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtnSubmitUserName item info.
            /// </summary>
            [RepositoryItemInfo("ce836688-52c1-4bf4-9170-91811c99d76d")]
            public virtual RepoItemInfo BtnSubmitUserNameInfo
            {
                get
                {
                    return _btnsubmitusernameInfo;
                }
            }

            /// <summary>
            /// The Reset item.
            /// </summary>
            [RepositoryItem("abc85cba-b18c-43d6-a0d8-3ae2585e0d66")]
            public virtual Ranorex.Link Reset
            {
                get
                {
                    return _resetInfo.CreateAdapter<Ranorex.Link>(true);
                }
            }

            /// <summary>
            /// The Reset item info.
            /// </summary>
            [RepositoryItemInfo("abc85cba-b18c-43d6-a0d8-3ae2585e0d66")]
            public virtual RepoItemInfo ResetInfo
            {
                get
                {
                    return _resetInfo;
                }
            }

            /// <summary>
            /// The LblWelcomeMessage item.
            /// </summary>
            [RepositoryItem("18a4556e-864a-4ab9-ab77-e5a7383da0b6")]
            public virtual Ranorex.Text LblWelcomeMessage
            {
                get
                {
                    return _lblwelcomemessageInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LblWelcomeMessage item info.
            /// </summary>
            [RepositoryItemInfo("18a4556e-864a-4ab9-ab77-e5a7383da0b6")]
            public virtual RepoItemInfo LblWelcomeMessageInfo
            {
                get
                {
                    return _lblwelcomemessageInfo;
                }
            }
        }

        /// <summary>
        /// The RxTabUploadFolder folder.
        /// </summary>
        [RepositoryFolder("bb3fa0c3-0933-476b-9e04-c47fd826449c")]
        public partial class RxTabUploadFolder : RepoGenBaseFolder
        {
            RepoItemInfo _rbslowInfo;
            RepoItemInfo _btnstartuploadInfo;
            RepoItemInfo _uploadprogressbarInfo;
            RepoItemInfo _lblfinishedInfo;
            RepoItemInfo _resetuploadInfo;

            /// <summary>
            /// Creates a new RxTabUpload  folder.
            /// </summary>
            public RxTabUploadFolder(RepoGenBaseFolder parentFolder) :
                    base("RxTabUpload", "?/?/tabpage[@controlname='RxTabUpload']", parentFolder, 30000, null, false, "bb3fa0c3-0933-476b-9e04-c47fd826449c", "")
            {
                _rbslowInfo = new RepoItemInfo(this, "RBSlow", "?/?/radiobutton[@controlname='rBSlow']", 30000, null, "82b12166-dd10-4f0c-8145-5d9f225f9008");
                _btnstartuploadInfo = new RepoItemInfo(this, "BtnStartUpload", "button[@controlname='btnStartUpload']", 30000, null, "7b42bb9d-5f99-4b9f-985f-b95160e5e03c");
                _uploadprogressbarInfo = new RepoItemInfo(this, "UploadProgressbar", "progressbar[@controlname='uploadProgressbar']", 30000, null, "2ce68793-123e-4897-82a4-49593d8f063d");
                _lblfinishedInfo = new RepoItemInfo(this, "LblFinished", "text[@controlname='lblFinished']", 30000, null, "ed12c5d4-c4e1-49dd-961b-168ee60d5895");
                _resetuploadInfo = new RepoItemInfo(this, "ResetUpload", "?/?/element[@accessiblename='Reset upload']", 30000, null, "8c68ae2e-4862-4708-bf61-7d8a75717a95");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("bb3fa0c3-0933-476b-9e04-c47fd826449c")]
            public virtual Ranorex.TabPage Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("bb3fa0c3-0933-476b-9e04-c47fd826449c")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The RBSlow item.
            /// </summary>
            [RepositoryItem("82b12166-dd10-4f0c-8145-5d9f225f9008")]
            public virtual Ranorex.RadioButton RBSlow
            {
                get
                {
                    return _rbslowInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The RBSlow item info.
            /// </summary>
            [RepositoryItemInfo("82b12166-dd10-4f0c-8145-5d9f225f9008")]
            public virtual RepoItemInfo RBSlowInfo
            {
                get
                {
                    return _rbslowInfo;
                }
            }

            /// <summary>
            /// The BtnStartUpload item.
            /// </summary>
            [RepositoryItem("7b42bb9d-5f99-4b9f-985f-b95160e5e03c")]
            public virtual Ranorex.Button BtnStartUpload
            {
                get
                {
                    return _btnstartuploadInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtnStartUpload item info.
            /// </summary>
            [RepositoryItemInfo("7b42bb9d-5f99-4b9f-985f-b95160e5e03c")]
            public virtual RepoItemInfo BtnStartUploadInfo
            {
                get
                {
                    return _btnstartuploadInfo;
                }
            }

            /// <summary>
            /// The UploadProgressbar item.
            /// </summary>
            [RepositoryItem("2ce68793-123e-4897-82a4-49593d8f063d")]
            public virtual Ranorex.ProgressBar UploadProgressbar
            {
                get
                {
                    return _uploadprogressbarInfo.CreateAdapter<Ranorex.ProgressBar>(true);
                }
            }

            /// <summary>
            /// The UploadProgressbar item info.
            /// </summary>
            [RepositoryItemInfo("2ce68793-123e-4897-82a4-49593d8f063d")]
            public virtual RepoItemInfo UploadProgressbarInfo
            {
                get
                {
                    return _uploadprogressbarInfo;
                }
            }

            /// <summary>
            /// The LblFinished item.
            /// </summary>
            [RepositoryItem("ed12c5d4-c4e1-49dd-961b-168ee60d5895")]
            public virtual Ranorex.Text LblFinished
            {
                get
                {
                    return _lblfinishedInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LblFinished item info.
            /// </summary>
            [RepositoryItemInfo("ed12c5d4-c4e1-49dd-961b-168ee60d5895")]
            public virtual RepoItemInfo LblFinishedInfo
            {
                get
                {
                    return _lblfinishedInfo;
                }
            }

            /// <summary>
            /// The ResetUpload item.
            /// </summary>
            [RepositoryItem("8c68ae2e-4862-4708-bf61-7d8a75717a95")]
            public virtual Ranorex.Unknown ResetUpload
            {
                get
                {
                    return _resetuploadInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The ResetUpload item info.
            /// </summary>
            [RepositoryItemInfo("8c68ae2e-4862-4708-bf61-7d8a75717a95")]
            public virtual RepoItemInfo ResetUploadInfo
            {
                get
                {
                    return _resetuploadInfo;
                }
            }
        }

        /// <summary>
        /// The RxTabUIElementsFolder folder.
        /// </summary>
        [RepositoryFolder("fdebd0ee-f338-4434-a04f-843fa5704081")]
        public partial class RxTabUIElementsFolder : RepoGenBaseFolder
        {
            RepoItemInfo _positionInfo;
            RepoItemInfo _linedownInfo;
            RepoItemInfo _lineupInfo;
            RepoItemInfo _treeviewInfo;
            RepoItemInfo _rdbgreenlightInfo;
            RepoItemInfo _pnlcolourpanelInfo;
            RepoItemInfo _rdbredlightInfo;
            RepoItemInfo _btnbutton1Info;
            RepoItemInfo _downInfo;
            RepoItemInfo _webtestingInfo;

            /// <summary>
            /// Creates a new RxTabUIElements  folder.
            /// </summary>
            public RxTabUIElementsFolder(RepoGenBaseFolder parentFolder) :
                    base("RxTabUIElements", "?/?/tabpage[@controlname='RxTabUIElements']", parentFolder, 30000, null, false, "fdebd0ee-f338-4434-a04f-843fa5704081", "")
            {
                _positionInfo = new RepoItemInfo(this, "Position", "?/?/scrollbar[@controlname='horizScrollBar']/indicator[@accessiblename='Position']", 30000, null, "6009f359-dc79-43fa-8b4e-627b48095bc4");
                _linedownInfo = new RepoItemInfo(this, "LineDown", "?/?/scrollbar[@controlname='vertScrollBar']/button[@accessiblename='Line down']", 30000, null, "3a330d69-23fd-4c36-b6df-4d9ea6dea5a0");
                _lineupInfo = new RepoItemInfo(this, "LineUp", "?/?/scrollbar[@controlname='vertScrollBar']/button[@accessiblename='Line up']", 30000, null, "2a3448e8-2ceb-4f0b-a8fb-31ef2056b44d");
                _treeviewInfo = new RepoItemInfo(this, "TreeView", "?/?/tree[@accessiblename='Tree view']", 30000, null, "37c213ff-6721-418f-b6b2-915f6955f77d");
                _rdbgreenlightInfo = new RepoItemInfo(this, "RdbGreenLight", "container[@controlname='grpBox']/?/?/radiobutton[@controlname='rdbGreenLight']", 30000, null, "5d7d379a-bc3b-405b-a71e-91727dcbd0b7");
                _pnlcolourpanelInfo = new RepoItemInfo(this, "PnlColourPanel", "container[@controlname='grpBox']/?/?/container[@controlname='pnlColourPanel']", 30000, null, "35c5f164-846b-47a3-beef-839709484bcd");
                _rdbredlightInfo = new RepoItemInfo(this, "RdbRedLight", "container[@controlname='grpBox']/?/?/radiobutton[@controlname='rdbRedLight']", 30000, null, "c94ab13e-26a4-4137-b94c-f02ae7f253ea");
                _btnbutton1Info = new RepoItemInfo(this, "BtnButton1", "?/?/button[@controlname='btnButton1']", 30000, null, "2829c9b2-8cbe-4588-8f31-e5eb5d0dab9d");
                _downInfo = new RepoItemInfo(this, "Down", "container[@controlname='grpBox']/?/?/list[@controlname='lstTestBox']/?/?/button[@text='Down']", 30000, null, "458c4049-22dc-486d-b2b1-66babc3c188b");
                _webtestingInfo = new RepoItemInfo(this, "WebTesting", "tree[@controlname='treTestTreeView']//treeitem[@accessiblename='Web testing']", 30000, null, "b974a462-3baf-4a50-b63c-931124b4647b");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("fdebd0ee-f338-4434-a04f-843fa5704081")]
            public virtual Ranorex.TabPage Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("fdebd0ee-f338-4434-a04f-843fa5704081")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Position item.
            /// </summary>
            [RepositoryItem("6009f359-dc79-43fa-8b4e-627b48095bc4")]
            public virtual Ranorex.Indicator Position
            {
                get
                {
                    return _positionInfo.CreateAdapter<Ranorex.Indicator>(true);
                }
            }

            /// <summary>
            /// The Position item info.
            /// </summary>
            [RepositoryItemInfo("6009f359-dc79-43fa-8b4e-627b48095bc4")]
            public virtual RepoItemInfo PositionInfo
            {
                get
                {
                    return _positionInfo;
                }
            }

            /// <summary>
            /// The LineDown item.
            /// </summary>
            [RepositoryItem("3a330d69-23fd-4c36-b6df-4d9ea6dea5a0")]
            public virtual Ranorex.Button LineDown
            {
                get
                {
                    return _linedownInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The LineDown item info.
            /// </summary>
            [RepositoryItemInfo("3a330d69-23fd-4c36-b6df-4d9ea6dea5a0")]
            public virtual RepoItemInfo LineDownInfo
            {
                get
                {
                    return _linedownInfo;
                }
            }

            /// <summary>
            /// The LineUp item.
            /// </summary>
            [RepositoryItem("2a3448e8-2ceb-4f0b-a8fb-31ef2056b44d")]
            public virtual Ranorex.Button LineUp
            {
                get
                {
                    return _lineupInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The LineUp item info.
            /// </summary>
            [RepositoryItemInfo("2a3448e8-2ceb-4f0b-a8fb-31ef2056b44d")]
            public virtual RepoItemInfo LineUpInfo
            {
                get
                {
                    return _lineupInfo;
                }
            }

            /// <summary>
            /// The TreeView item.
            /// </summary>
            [RepositoryItem("37c213ff-6721-418f-b6b2-915f6955f77d")]
            public virtual Ranorex.Tree TreeView
            {
                get
                {
                    return _treeviewInfo.CreateAdapter<Ranorex.Tree>(true);
                }
            }

            /// <summary>
            /// The TreeView item info.
            /// </summary>
            [RepositoryItemInfo("37c213ff-6721-418f-b6b2-915f6955f77d")]
            public virtual RepoItemInfo TreeViewInfo
            {
                get
                {
                    return _treeviewInfo;
                }
            }

            /// <summary>
            /// The RdbGreenLight item.
            /// </summary>
            [RepositoryItem("5d7d379a-bc3b-405b-a71e-91727dcbd0b7")]
            public virtual Ranorex.RadioButton RdbGreenLight
            {
                get
                {
                    return _rdbgreenlightInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The RdbGreenLight item info.
            /// </summary>
            [RepositoryItemInfo("5d7d379a-bc3b-405b-a71e-91727dcbd0b7")]
            public virtual RepoItemInfo RdbGreenLightInfo
            {
                get
                {
                    return _rdbgreenlightInfo;
                }
            }

            /// <summary>
            /// The PnlColourPanel item.
            /// </summary>
            [RepositoryItem("35c5f164-846b-47a3-beef-839709484bcd")]
            public virtual Ranorex.Container PnlColourPanel
            {
                get
                {
                    return _pnlcolourpanelInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The PnlColourPanel item info.
            /// </summary>
            [RepositoryItemInfo("35c5f164-846b-47a3-beef-839709484bcd")]
            public virtual RepoItemInfo PnlColourPanelInfo
            {
                get
                {
                    return _pnlcolourpanelInfo;
                }
            }

            /// <summary>
            /// The RdbRedLight item.
            /// </summary>
            [RepositoryItem("c94ab13e-26a4-4137-b94c-f02ae7f253ea")]
            public virtual Ranorex.RadioButton RdbRedLight
            {
                get
                {
                    return _rdbredlightInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The RdbRedLight item info.
            /// </summary>
            [RepositoryItemInfo("c94ab13e-26a4-4137-b94c-f02ae7f253ea")]
            public virtual RepoItemInfo RdbRedLightInfo
            {
                get
                {
                    return _rdbredlightInfo;
                }
            }

            /// <summary>
            /// The BtnButton1 item.
            /// </summary>
            [RepositoryItem("2829c9b2-8cbe-4588-8f31-e5eb5d0dab9d")]
            public virtual Ranorex.Button BtnButton1
            {
                get
                {
                    return _btnbutton1Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtnButton1 item info.
            /// </summary>
            [RepositoryItemInfo("2829c9b2-8cbe-4588-8f31-e5eb5d0dab9d")]
            public virtual RepoItemInfo BtnButton1Info
            {
                get
                {
                    return _btnbutton1Info;
                }
            }

            /// <summary>
            /// The Down item.
            /// </summary>
            [RepositoryItem("458c4049-22dc-486d-b2b1-66babc3c188b")]
            public virtual Ranorex.Button Down
            {
                get
                {
                    return _downInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Down item info.
            /// </summary>
            [RepositoryItemInfo("458c4049-22dc-486d-b2b1-66babc3c188b")]
            public virtual RepoItemInfo DownInfo
            {
                get
                {
                    return _downInfo;
                }
            }

            /// <summary>
            /// The WebTesting item.
            /// </summary>
            [RepositoryItem("b974a462-3baf-4a50-b63c-931124b4647b")]
            public virtual Ranorex.TreeItem WebTesting
            {
                get
                {
                    return _webtestingInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The WebTesting item info.
            /// </summary>
            [RepositoryItemInfo("b974a462-3baf-4a50-b63c-931124b4647b")]
            public virtual RepoItemInfo WebTestingInfo
            {
                get
                {
                    return _webtestingInfo;
                }
            }
        }

        /// <summary>
        /// The DataGridView1Folder folder.
        /// </summary>
        [RepositoryFolder("72cf1af4-47cb-4905-8594-83c2002d30d5")]
        public partial class DataGridView1Folder : RepoGenBaseFolder
        {
            RepoItemInfo _firstnamerow0Info;
            RepoItemInfo _iorow0Info;
            RepoItemInfo _lastnamerow0Info;
            RepoItemInfo _row0Info;
            RepoItemInfo _datagridviewtextboxeditingcontrolInfo;
            RepoItemInfo _iorow7Info;
            RepoItemInfo _row7Info;
            RepoItemInfo _firstnamerow7Info;

            /// <summary>
            /// Creates a new DataGridView1  folder.
            /// </summary>
            public DataGridView1Folder(RepoGenBaseFolder parentFolder) :
                    base("DataGridView1", "?/?/tabpage[@controlname='RxTabUIElements']/table[@controlname='dataGridView1']", parentFolder, 30000, null, false, "72cf1af4-47cb-4905-8594-83c2002d30d5", "")
            {
                _firstnamerow0Info = new RepoItemInfo(this, "FirstNameRow0", "?/?/cell[@accessiblename='FirstName Row 0']", 30000, null, "e5bd3ca0-a237-46fe-8543-2823b8b1edb6");
                _iorow0Info = new RepoItemInfo(this, "IORow0", "?/?/cell[@accessiblename='IO Row 0']", 30000, null, "6e650e0a-2b8d-4947-88c2-e8fd494083f3");
                _lastnamerow0Info = new RepoItemInfo(this, "LastNameRow0", "?/?/cell[@accessiblename='LastName Row 0']", 30000, null, "4ec581a0-3f7a-4735-a562-b1dbd59d97ef");
                _row0Info = new RepoItemInfo(this, "Row0", "?/?/cell[@accessiblename='Row 0']", 30000, null, "29d6d355-5c43-46bb-ade1-d5ca230d49e5");
                _datagridviewtextboxeditingcontrolInfo = new RepoItemInfo(this, "DataGridViewTextBoxEditingControl", "?/?/text[@controltypename='DataGridViewTextBoxEditingControl']", 30000, null, "d2370331-650b-4eca-a256-02d28f53f8ae");
                _iorow7Info = new RepoItemInfo(this, "IORow7", "?/?/cell[@accessiblename='IO Row 7']", 30000, null, "01684087-a218-4b8e-822f-061d3ff321c1");
                _row7Info = new RepoItemInfo(this, "Row7", "?/?/cell[@accessiblename='Row 7']", 30000, null, "0a6dac60-3671-44a5-bb7a-52916f6bde71");
                _firstnamerow7Info = new RepoItemInfo(this, "FirstNameRow7", "?/?/cell[@accessiblename='FirstName Row 7']", 30000, null, "59895906-92a0-4f05-abff-c6d46a60f41a");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("72cf1af4-47cb-4905-8594-83c2002d30d5")]
            public virtual Ranorex.Table Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Table>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("72cf1af4-47cb-4905-8594-83c2002d30d5")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The FirstNameRow0 item.
            /// </summary>
            [RepositoryItem("e5bd3ca0-a237-46fe-8543-2823b8b1edb6")]
            public virtual Ranorex.Cell FirstNameRow0
            {
                get
                {
                    return _firstnamerow0Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The FirstNameRow0 item info.
            /// </summary>
            [RepositoryItemInfo("e5bd3ca0-a237-46fe-8543-2823b8b1edb6")]
            public virtual RepoItemInfo FirstNameRow0Info
            {
                get
                {
                    return _firstnamerow0Info;
                }
            }

            /// <summary>
            /// The IORow0 item.
            /// </summary>
            [RepositoryItem("6e650e0a-2b8d-4947-88c2-e8fd494083f3")]
            public virtual Ranorex.Cell IORow0
            {
                get
                {
                    return _iorow0Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The IORow0 item info.
            /// </summary>
            [RepositoryItemInfo("6e650e0a-2b8d-4947-88c2-e8fd494083f3")]
            public virtual RepoItemInfo IORow0Info
            {
                get
                {
                    return _iorow0Info;
                }
            }

            /// <summary>
            /// The LastNameRow0 item.
            /// </summary>
            [RepositoryItem("4ec581a0-3f7a-4735-a562-b1dbd59d97ef")]
            public virtual Ranorex.Cell LastNameRow0
            {
                get
                {
                    return _lastnamerow0Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The LastNameRow0 item info.
            /// </summary>
            [RepositoryItemInfo("4ec581a0-3f7a-4735-a562-b1dbd59d97ef")]
            public virtual RepoItemInfo LastNameRow0Info
            {
                get
                {
                    return _lastnamerow0Info;
                }
            }

            /// <summary>
            /// The Row0 item.
            /// </summary>
            [RepositoryItem("29d6d355-5c43-46bb-ade1-d5ca230d49e5")]
            public virtual Ranorex.Cell Row0
            {
                get
                {
                    return _row0Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The Row0 item info.
            /// </summary>
            [RepositoryItemInfo("29d6d355-5c43-46bb-ade1-d5ca230d49e5")]
            public virtual RepoItemInfo Row0Info
            {
                get
                {
                    return _row0Info;
                }
            }

            /// <summary>
            /// The DataGridViewTextBoxEditingControl item.
            /// </summary>
            [RepositoryItem("d2370331-650b-4eca-a256-02d28f53f8ae")]
            public virtual Ranorex.Text DataGridViewTextBoxEditingControl
            {
                get
                {
                    return _datagridviewtextboxeditingcontrolInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The DataGridViewTextBoxEditingControl item info.
            /// </summary>
            [RepositoryItemInfo("d2370331-650b-4eca-a256-02d28f53f8ae")]
            public virtual RepoItemInfo DataGridViewTextBoxEditingControlInfo
            {
                get
                {
                    return _datagridviewtextboxeditingcontrolInfo;
                }
            }

            /// <summary>
            /// The IORow7 item.
            /// </summary>
            [RepositoryItem("01684087-a218-4b8e-822f-061d3ff321c1")]
            public virtual Ranorex.Cell IORow7
            {
                get
                {
                    return _iorow7Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The IORow7 item info.
            /// </summary>
            [RepositoryItemInfo("01684087-a218-4b8e-822f-061d3ff321c1")]
            public virtual RepoItemInfo IORow7Info
            {
                get
                {
                    return _iorow7Info;
                }
            }

            /// <summary>
            /// The Row7 item.
            /// </summary>
            [RepositoryItem("0a6dac60-3671-44a5-bb7a-52916f6bde71")]
            public virtual Ranorex.Cell Row7
            {
                get
                {
                    return _row7Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The Row7 item info.
            /// </summary>
            [RepositoryItemInfo("0a6dac60-3671-44a5-bb7a-52916f6bde71")]
            public virtual RepoItemInfo Row7Info
            {
                get
                {
                    return _row7Info;
                }
            }

            /// <summary>
            /// The FirstNameRow7 item.
            /// </summary>
            [RepositoryItem("59895906-92a0-4f05-abff-c6d46a60f41a")]
            public virtual Ranorex.Cell FirstNameRow7
            {
                get
                {
                    return _firstnamerow7Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The FirstNameRow7 item info.
            /// </summary>
            [RepositoryItemInfo("59895906-92a0-4f05-abff-c6d46a60f41a")]
            public virtual RepoItemInfo FirstNameRow7Info
            {
                get
                {
                    return _firstnamerow7Info;
                }
            }
        }

    }
#pragma warning restore 0436
}
