///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace TCOS_POC_DEMOAPP
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the TCOS_POC_DEMOAPPRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("95af092a-f552-4cd1-bced-e40668d18b4e")]
    public partial class TCOS_POC_DEMOAPPRepository : RepoGenBaseFolder
    {
        static TCOS_POC_DEMOAPPRepository instance = new TCOS_POC_DEMOAPPRepository();

        /// <summary>
        /// Gets the singleton class instance representing the TCOS_POC_DEMOAPPRepository element repository.
        /// </summary>
        [RepositoryFolder("95af092a-f552-4cd1-bced-e40668d18b4e")]
        public static TCOS_POC_DEMOAPPRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public TCOS_POC_DEMOAPPRepository() 
            : base("TCOS_POC_DEMOAPPRepository", "/", null, 0, false, "95af092a-f552-4cd1-bced-e40668d18b4e", ".\\RepositoryImages\\TCOS_POC_DEMOAPPRepository95af092a.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("95af092a-f552-4cd1-bced-e40668d18b4e")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class TCOS_POC_DEMOAPPRepositoryFolders
    {
    }
#pragma warning restore 0436
}
